spring:
    datasource:
        url: jdbc:mysql://192.168.4.43:3306/spring?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
        username: spring
        password: spring
    redis:
        host: 192.168.4.43
        password:
    rabbitmq:
        host: 192.168.4.43