spring:
    datasource:
        url: jdbc:mysql://10.25.1.252:3306/fuwo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
    jpa:
        show-sql: false
        properties:
            hibernate:
                hbm2ddl.auto: validate
    redis:
        host: 10.116.199.27
        database: 5

security:
    oauth2:
        client:
            client-id: client1
            client-secret: 9jWlaEHVLGEyeQaDzaeaLcgvcCCyPz98

server:
    port: 9000
    error:
        whitelabel:
            enabled: false

oss:
    domain : http://img.fuwo.com/
    image:
        bucket-name: fuwo-img
        bucket-access-key: LTAIsJFOVobiTGNE
        bucket-access-secret: xqYHtHDDkjDUIE9KX65OzVGAcMhtAZ