spring:
    datasource:
        url: jdbc:mysql://192.168.2.133:3306/fuwo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
        username: root
        password: 123456
    redis:
        host: 192.168.2.221

server :
    port: 9000

logging:
    level:
        org.springframework: DEBUG
